# Día 4 IMÁGENES (づ｡◕‿‿◕｡)づ

El manual de la librería MATPLOTLIB se encuentra en https://matplotlib.org/users/image_tutorial.html

El manual de la librería NUMPY se encuentra en https://numpy.org/doc/stable/user/index.html

## Numpy y matplotlib

### Importando librerías

Numpy es una librería que permite un manejo intuitivo de las variables tipo lista. Para acceder a estas funciones es necesario definir las listas como un **arreglo** de numpy. Esta librería también ofrece opciones para definir estas estructuras de tipo arreglo. 

Recordemos que siempre que vayamos a usar una librería nueva, se debe importar mediante los comandos "import *librería*".

In [38]:
import numpy

Esto hará que debamos llamar a las funciones usando la sintaxis librería.funcion(variables, a , usar)

In [ ]:
numpy.power(2,3)

In [ ]:
print(numpy.power(2,3))

Este tipo de llamado a las funciones puede parecer breve, pero existen librerías como matplotlib que tienen una mayor cantidad de caracteres en su nombre y que pueden conllevar a un mayor desgaste. Debido a esto existe una sintaxis que permite asignar **apodos** a las librerías que se están importando, esta es "import *librería* as *apodo*"

In [14]:
import numpy as np

El uso será similar al anterior, pero ahora para llamar las funciones de la librería no se necesita colocar su nombre completo, sino su apodo "apodo.funcion(variables, a, usar)"

In [ ]:
np.power(2,3)

In [ ]:
print(numpy.power(2,3))

En estos dos casos se ha llamado toda la librería. Esto quiere decir que se ha podido accesar a todas las funciones de la librería, incluyendo aquellas que **no se van a usar**, lo cual a la larga puede cargar innecesariamente la memoria. Dado esto, existe una forma de llamar específicamente funciones usando "from *librería* import *función*". 

In [3]:
from numpy import power

In [2]:
power(2,3)

np.int64(27)

Finalmente, lo que hemos aprendido se puede combinar para colocar un apodo a esta función que se ha importado.

In [4]:
from numpy import power as pw

In [5]:
pw(2,3)

np.int64(9)

### ¿Para qué usar numpy?

Ya hemos dicho que esta librería tiene en sus principales características un manejo intuitivo de las variables de tipo lista, las cuales se llaman **arreglos** en numpy. Antes de entrar en esto, vamos a definir una lista que contenga tres datos.

In [36]:
import numpy as np

lista_f = [1, 2, 3]

Esto es lo que se conoce como una **fila**, pues permite arreglar los datos uno tras otro de manera horizontal, como cuando uno va al banco.

In [37]:
lista_f

[1, 2, 3]

Por curiosidad, miremos qué pasa al multiplicar esta lista por el número 2.

In [41]:
lista_f*2

[1, 2, 3, 1, 2, 3]

Se puede convertir una lista de python en un arreglo de numpy mediante el comando "numpy.array(lista)". Acá usaremos la sintaxis con el apodo np.

In [43]:
lista_f = np.array(lista_f)

Ahora estos datos pueden procesarse de manera sencilla indicando operaciones con números enteros, lo que aplicará la operación a todos los números del arreglo.

In [44]:
lista_f + 2

array([3, 4, 5])

In [45]:
lista_f * 2

array([2, 4, 6])

Otra manera de estructurar los datos es a partir de la definición de columnas, que permite arreglar los datos uno encima de otro, como los pilares de las construcciones permiten colocar un piso encima de otro. Esto se logra definiendo inicialmente una lista de listas, así.

[ [piso 1] , [piso 2] , [etc.] ]

In [46]:
lista_c = [[1],[2],[3]]

In [47]:
print(lista_c)

[[1], [2], [3]]


Ya tenemos una lista de listas. Finalmente, tenemos que pasar este tipo de arreglo a otra estructura que nos permite visibilizar los datos como filas y como columna, el cual recibe el nombre de matriz o matrix (sí, como la película).

In [48]:
print(f'''Esto es una fila 
{np.matrix(lista_f)}

Y esto es una columna
{np.matrix(lista_c)}''')

Esto es una fila 
[[1 2 3]]

Y esto es una columna
[[1]
 [2]
 [3]]


Dejemos este tipo de arreglo en el tintero y vamos a otro con el que podamos enlazar también a la libería *matplotlib*. El comando *linspace(int_inicial, int_final, pasos)* es muy similar al *range()* que ya conocemos y se usa para generar una lista que nos de números desde un **entero inicial** hasta un **entero final** espaciados por **pasos** números.

In [31]:
x = np.linspace(-3,3,21)

In [33]:
x

array([-3. , -2.7, -2.4, -2.1, -1.8, -1.5, -1.2, -0.9, -0.6, -0.3,  0. ,
        0.3,  0.6,  0.9,  1.2,  1.5,  1.8,  2.1,  2.4,  2.7,  3. ])

In [34]:
type(x)

numpy.ndarray

También podemos acceder a datos específicos con la sintaxis "arreglo[índice del dato]".

In [35]:
x[1]

np.float64(-2.7)

In [ ]:
def recta(x, m, b):
    
    y = m * x + b
    
    return y

In [ ]:
y = recta(x, 1, 0) 

Matplotlib es una librería que permite hacer distintos tipos de gráficos y manipular algunas de las características que pueden llegar a ser necesarias como títulos, etiquetas, tamaños, etc.

In [ ]:
import matplotlib

In [ ]:
plt.plot(x,y)
plt.axis('equal')

In [ ]:
plt.scatter(x,y)

plt.axis('equal')

In [ ]:
plt.title("Una bonita recta")

plt.xlabel("eje x")
plt.ylabel("eje y");

plt.plot( x, recta(x,1,0), label= "m=1, b=0")

plt.legend()
plt.axis('equal')

In [ ]:
plt.title("Varias bonitas rectas")

plt.xlabel("eje x")
plt.ylabel("eje y");

plt.plot( x, recta(x,1,0), label= "m=1, b=0")
plt.plot( x, recta(x,0,0), label= "m=0, b=0")
plt.plot( x, recta(x,-2,0), label= "m=-2, b=0")


plt.legend()
plt.axis('equal')

In [ ]:
fig = plt.figure(figsize=[7,7])
plt.xlim(-3,3)
plt.ylim(-3,3)

plt.title("Varias rectas muy bonitas")

plt.xlabel("eje x")
plt.ylabel("eje y");

plt.plot( x, recta(x,1,0), label= "m=1, b=0")
plt.plot( x, recta(x,0,0), label= "m=0, b=0")
plt.plot( x, recta(x,-2,0), label= "m=-2, b=0")

plt.legend()

In [ ]:
fig = plt.figure(figsize=[7,7])
plt.xlim(-3,3)
plt.ylim(-3,3)

plt.title("Varias rectas muy bonitas")

plt.xlabel("eje x")
plt.ylabel("eje y");

plt.plot( x, recta(x,1,0), label= "m=1, b=0")
plt.plot( x, recta(x,1,2), label= "m=1, b=2")
plt.plot( x, recta(x,1,4), label= "m=1, b=4")

plt.legend()

In [ ]:
def cuadratica(x,a,b,c):
    y = a*x**2 + b*x + c
    return y

In [ ]:
fig = plt.figure(figsize=[7,7])
plt.xlim(-3,3)
plt.ylim(-3,3)


plt.title("Una función muy cuadrática")

plt.xlabel("eje x")
plt.ylabel("eje y");

plt.plot( x, cuadratica(x,2,-1,-1), label= "$2 x^2 - x - 1$")

plt.legend()

In [ ]:
fig = plt.figure(figsize=[7,7])
plt.xlim(-3,3)
plt.ylim(-3,3)


plt.title("Muchas curvas muy cuadráticas")

plt.xlabel("eje x")
plt.ylabel("eje y");

plt.plot( x, cuadratica(x,2,-1,-1), label= "$2 x^2 - x - 1$")
plt.plot( x, cuadratica(x,-2,+1,+2), label= "$-2 x^2 + x + 2$")


plt.legend()

# Sesión 4

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.pyplot import imshow
from matplotlib import figure

In [23]:
matrix = np.array([[0,1],[2,3]])

In [ ]:
print(matrix)

In [ ]:
plt.imshow(matrix)

In [25]:
matrix = np.array([
    [ 0, 1, 2, 3, 4],
    [ 5, 6, 7, 8, 9],
    [ 10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]])

In [ ]:
plt.imshow(matrix)

In [ ]:
plt.imshow(matrix, cmap='gray')

In [ ]:
plt.imshow(matrix)

In [19]:
matrix2 = np.zeros([16,16])

In [20]:
matrix = np.array([
    [ 0, 1, 0, 1, 0],
    [ 0, 0, 0, 0, 0],
    [ 1, 0, 0, 0, 1],
    [0, 1, 1, 1, 0]])

In [ ]:
matrix2

In [ ]:
plt.imshow(matrix2)

In [ ]:
plt.imshow(matrix2, cmap="gray")

In [ ]:
matrix2[0,0]=1
plt.imshow(matrix2, cmap="gray")

In [ ]:
matrix2[8,8]=1
plt.imshow(matrix2, cmap="gray")

In [33]:
matrix2[:]=0

In [ ]:
plt.imshow(matrix2, cmap="gray")

# Ejercicios

1. Poner la fila 1 en color blanco
2. Poner la columna 1 en color blanco

In [ ]:
for i in range(16):
    matrix2[0,i]=1
plt.imshow(matrix2, cmap="gray")

In [ ]:
for i in range(16):
    matrix2[i,0]=1
plt.imshow(matrix2, cmap="gray")

In [ ]:
contador=0
for i in range(16):
    for j in range (16):
        matrix2[i,j]=contador
        contador +=1
plt.imshow(matrix2,cmap="gray")

In [ ]:
matrix2

In [5]:
img=mpimg.imread('images/paisaje.png')

In [ ]:
img

In [ ]:
imgplot = plt.imshow(img)
# Mapas de colores en https://matplotlib.org/examples/color/colormaps_reference.html

In [ ]:
imgplot = plt.imshow(img, cmap='gray')

In [ ]:
imgplot = plt.imshow(img, cmap='hsv')

In [ ]:
img.shape

In [ ]:
img.size